git: 
  depth: false
  quiet: false
language: generic
dist: bionic 
sudo: required
 
branches:
  only:
    - /dev*/
    - /AO-dev*/
    - /QA*/
    - /QE*/
    - /RC*/
    - /Release-Master*/

env:
- SHORT_COMMIT= `git rev-parse --short=7 ${TRAVIS_COMMIT}`

before_install:

  - echo $TRAVIS_BRANCH
  - echo $PWD
  - echo $TRAVIS_COMMIT
  - echo $BUILD_REPO_NAME
jobs:
  include:

    script: 

  - chmod u+x publish_package.sh && bash publish_package.sh  

notifications:
  email:
    recipients:
      - harasunu.narayan@froala.com

    on_success: always 
    on_failure: always 
